/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the API
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List alerts
         * @description Retrieve a paginated list of trading alerts with optional filtering
         */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get alert statistics
         * @description Retrieve aggregated statistics about alerts
         */
        get: operations["getAlertStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get alert by ID
         * @description Retrieve a single alert by its ID
         */
        get: operations["getAlert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update alert
         * @description Update alert properties (e.g., mark as read)
         */
        patch: operations["updateAlert"];
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all rules
         * @description Retrieve all trading rules
         */
        get: operations["listRules"];
        put?: never;
        /**
         * Create a new rule
         * @description Create a new trading rule with YAML configuration
         */
        post: operations["createRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get rule by ID
         * @description Retrieve a single rule by its ID
         */
        get: operations["getRule"];
        /**
         * Update rule
         * @description Update an existing trading rule
         */
        put: operations["updateRule"];
        post?: never;
        /**
         * Delete rule
         * @description Delete a trading rule
         */
        delete: operations["deleteRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{rule_id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle rule active status
         * @description Enable or disable a trading rule
         */
        post: operations["toggleRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get watchlist
         * @description Retrieve all symbols in the watchlist
         */
        get: operations["getWatchlist"];
        put?: never;
        /**
         * Add to watchlist
         * @description Add a symbol to the watchlist
         */
        post: operations["addToWatchlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove from watchlist
         * @description Remove a symbol from the watchlist
         */
        delete: operations["removeFromWatchlist"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market-data/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current market data
         * @description Retrieve current market data for a symbol
         */
        get: operations["getMarketData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market-data/{symbol}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get historical bars
         * @description Retrieve historical OHLCV bars for a symbol
         */
        get: operations["getHistoricalBars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @example healthy
             * @enum {string}
             */
            status: "healthy" | "degraded" | "unhealthy";
            /** Format: date-time */
            timestamp: string;
            /** @example 1.0.0 */
            version?: string;
            /** @example true */
            alpaca_connected?: boolean;
            /** @example true */
            database_connected?: boolean;
        };
        Alert: {
            /** @example 123 */
            id: number;
            /** @example 5 */
            rule_id?: number | null;
            /** @example breakout_setup */
            rule_name?: string | null;
            /** @example AAPL */
            symbol: string;
            /**
             * Format: date-time
             * @description When the alert condition was triggered
             */
            timestamp: string;
            /**
             * @example breakout
             * @enum {string}
             */
            setup_type: "breakout" | "volume_spike" | "gap_up" | "gap_down" | "momentum";
            /**
             * Format: float
             * @example 185.5
             */
            entry_price: number;
            /**
             * Format: float
             * @example 182
             */
            stop_loss?: number | null;
            /**
             * Format: float
             * @example 195
             */
            target_price?: number | null;
            /**
             * Format: float
             * @example 0.85
             */
            confidence_score?: number | null;
            market_data?: components["schemas"]["AlertMarketData"];
            /** @example false */
            is_read: boolean;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Snapshot of market data when alert was triggered */
        AlertMarketData: {
            /** Format: float */
            price?: number;
            volume?: number;
            /**
             * Format: float
             * @description Current volume / average volume
             */
            volume_ratio?: number;
            /** Format: float */
            day_high?: number;
            /** Format: float */
            day_low?: number;
            /** Format: float */
            pre_market_high?: number | null;
            /** @description Number of shares available for trading */
            float_shares?: number | null;
            /**
             * Format: float
             * @description Short interest ratio
             */
            short_interest?: number | null;
        };
        AlertListResponse: {
            items: components["schemas"]["Alert"][];
            /**
             * @description Total number of alerts matching the filter
             * @example 150
             */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 50 */
            page_size: number;
            /** @example true */
            has_next?: boolean;
            /** @example false */
            has_prev?: boolean;
        };
        AlertUpdate: {
            is_read?: boolean;
        };
        AlertStats: {
            /** @example 1250 */
            total_alerts: number;
            /** @example 15 */
            alerts_today: number;
            /** @example 8 */
            unread_count: number;
            /**
             * @example {
             *       "breakout": 450,
             *       "volume_spike": 380,
             *       "gap_up": 220,
             *       "momentum": 200
             *     }
             */
            by_setup_type?: {
                [key: string]: number;
            };
            /**
             * @example {
             *       "AAPL": 120,
             *       "TSLA": 95,
             *       "NVDA": 88
             *     }
             */
            by_symbol?: {
                [key: string]: number;
            };
            /**
             * Format: float
             * @example 0.72
             */
            avg_confidence?: number;
        };
        Rule: {
            /** @example 1 */
            id: number;
            /** @example breakout_setup */
            name: string;
            /** @example Price breakout above resistance with volume confirmation */
            description?: string | null;
            /**
             * @example price
             * @enum {string}
             */
            rule_type: "price" | "volume" | "gap" | "technical";
            /**
             * @description YAML configuration for the rule
             * @example conditions:
             *       - field: price
             *         operator: ">"
             *         value: resistance_level
             */
            config_yaml: string;
            /** @example true */
            is_active: boolean;
            /**
             * @description Higher priority rules are evaluated first
             * @example 10
             */
            priority: number;
            /**
             * @description Number of alerts this rule has triggered
             * @example 45
             */
            alerts_triggered?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RuleCreate: {
            /** @example my_custom_rule */
            name: string;
            description?: string;
            /** @enum {string} */
            rule_type: "price" | "volume" | "gap" | "technical";
            /** @description YAML configuration for the rule */
            config_yaml: string;
            /** @default true */
            is_active: boolean;
            /** @default 0 */
            priority: number;
        };
        RuleUpdate: {
            name?: string;
            description?: string;
            config_yaml?: string;
            is_active?: boolean;
            priority?: number;
        };
        WatchlistItem: {
            /** @example 1 */
            id: number;
            /** @example AAPL */
            symbol: string;
            /** Format: date-time */
            added_at: string;
            /** @example true */
            is_active: boolean;
            /** @example Watch for earnings breakout */
            notes?: string | null;
        };
        WatchlistCreate: {
            /** @example AAPL */
            symbol: string;
            notes?: string;
        };
        MarketData: {
            /** @example AAPL */
            symbol: string;
            /**
             * Format: float
             * @example 185.5
             */
            price: number;
            /**
             * Format: float
             * @example 185.48
             */
            bid?: number;
            /**
             * Format: float
             * @example 185.52
             */
            ask?: number;
            /** @example 100 */
            bid_size?: number;
            /** @example 200 */
            ask_size?: number;
            /** @example 45678900 */
            volume?: number;
            /** Format: date-time */
            timestamp: string;
            /**
             * Format: float
             * @description Price change from previous close
             * @example 2.5
             */
            change?: number;
            /**
             * Format: float
             * @description Percentage change from previous close
             * @example 1.37
             */
            change_percent?: number;
            /**
             * Format: float
             * @example 186.2
             */
            day_high?: number;
            /**
             * Format: float
             * @example 183.5
             */
            day_low?: number;
            /**
             * Format: float
             * @example 184
             */
            day_open?: number;
            /**
             * Format: float
             * @example 183
             */
            prev_close?: number;
            /**
             * Format: float
             * @example 185
             */
            pre_market_price?: number | null;
            /**
             * Format: float
             * @example 185.75
             */
            after_hours_price?: number | null;
            /**
             * Format: float
             * @description Volume-weighted average price
             * @example 184.85
             */
            vwap?: number;
        };
        Bar: {
            /** Format: date-time */
            timestamp: string;
            /**
             * Format: float
             * @example 184
             */
            open: number;
            /**
             * Format: float
             * @example 186.2
             */
            high: number;
            /**
             * Format: float
             * @example 183.5
             */
            low: number;
            /**
             * Format: float
             * @example 185.5
             */
            close: number;
            /** @example 1234567 */
            volume: number;
            /**
             * Format: float
             * @example 184.85
             */
            vwap?: number;
            /** @example 45678 */
            trade_count?: number;
        };
        ErrorResponse: {
            /** @example NOT_FOUND */
            error: string;
            /** @example Alert with ID 123 not found */
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        WebSocketClientMessage: {
            /** @enum {string} */
            action: "subscribe" | "unsubscribe";
            /** @enum {string} */
            channel?: "alerts" | "market_data";
            /** @description Required when channel is market_data */
            symbols?: string[];
        };
        WebSocketServerMessage: {
            /** @enum {string} */
            type: "alert" | "market_data" | "status" | "error";
            data?: Record<string, never>;
        };
        WebSocketAlertMessage: components["schemas"]["WebSocketServerMessage"] & {
            /** @enum {string} */
            type?: "alert";
            data?: components["schemas"]["Alert"];
        };
        WebSocketMarketDataMessage: components["schemas"]["WebSocketServerMessage"] & {
            /** @enum {string} */
            type?: "market_data";
            data?: components["schemas"]["MarketData"];
        };
        WebSocketStatusMessage: components["schemas"]["WebSocketServerMessage"] & {
            /** @enum {string} */
            type?: "status";
            data?: {
                connected?: boolean;
                subscriptions?: string[];
            };
        };
        WebSocketErrorMessage: components["schemas"]["WebSocketServerMessage"] & {
            /** @enum {string} */
            type?: "error";
            data?: {
                code?: string;
                message?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                /** @description Filter by ticker symbol */
                symbol?: string;
                /** @description Filter by setup type */
                setup_type?: "breakout" | "volume_spike" | "gap_up" | "gap_down" | "momentum";
                /** @description Filter alerts after this date */
                start_date?: string;
                /** @description Filter alerts before this date */
                end_date?: string;
                /** @description Filter by read status */
                is_read?: boolean;
                /** @description Page number (1-indexed) */
                page?: number;
                /** @description Number of items per page */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of alerts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
        };
    };
    getAlertStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStats"];
                };
            };
        };
    };
    getAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The alert ID */
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description Alert not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The alert ID */
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertUpdate"];
            };
        };
        responses: {
            /** @description Updated alert */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description Alert not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"][];
                };
            };
        };
    };
    createRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleCreate"];
            };
        };
        responses: {
            /** @description Created rule */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            /** @description Invalid rule configuration */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rule with this name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The rule ID */
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            /** @description Rule not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The rule ID */
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleUpdate"];
            };
        };
        responses: {
            /** @description Updated rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            /** @description Invalid rule configuration */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rule not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The rule ID */
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rule not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    toggleRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The rule ID */
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated rule with toggled status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            /** @description Rule not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getWatchlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Watchlist items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItem"][];
                };
            };
        };
    };
    addToWatchlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreate"];
            };
        };
        responses: {
            /** @description Added to watchlist */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItem"];
                };
            };
            /** @description Invalid symbol */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Symbol already in watchlist */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeFromWatchlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ticker symbol */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed from watchlist */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Symbol not in watchlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMarketData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ticker symbol */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current market data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketData"];
                };
            };
            /** @description Symbol not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHistoricalBars: {
        parameters: {
            query?: {
                /** @description Bar timeframe */
                timeframe?: "1Min" | "5Min" | "15Min" | "1Hour" | "1Day";
                /** @description Start datetime (ISO 8601) */
                start?: string;
                /** @description End datetime (ISO 8601) */
                end?: string;
                /** @description Maximum number of bars to return */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description The ticker symbol */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historical bars */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bar"][];
                };
            };
            /** @description Symbol not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
