"""Phase 3: v2 alert contract, scanner_settings

Revision ID: 0ca0181ab014
Revises: 5c3b382f1d74
Create Date: 2026-07-28 13:49:10.337257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca0181ab014'
down_revision: Union[str, Sequence[str], None] = '5c3b382f1d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-adjusted: the three NOT NULL additions below carry `server_default` so they
    backfill existing rows. Without it this migration fails on any populated `alerts`
    table — which is every environment that has ever run a scan, including Supabase.
    The defaults are kept afterwards so a raw INSERT outside the ORM stays valid.

    Note on the dedup constraint: Postgres treats NULLs as distinct in a UNIQUE
    constraint, so retained v1 rule-engine alerts (session_date IS NULL) can still repeat
    a symbol freely. Only v2 scanner alerts, which always set session_date, are deduped.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanner_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(length=30), nullable=True),
    sa.Column('overrides_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('alerts', sa.Column('updated_at', sa.DateTime(), nullable=False,
                                      server_default=sa.func.now()))
    op.add_column('alerts', sa.Column('scan_run_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('session_date', sa.Date(), nullable=True))
    op.add_column('alerts', sa.Column('profile', sa.String(length=30), nullable=True))
    op.add_column('alerts', sa.Column('gap_pct', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('rvol_pct', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('rvol_mode', sa.String(length=20), nullable=True))
    op.add_column('alerts', sa.Column('rvol_is_approximate', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
    op.add_column('alerts', sa.Column('catalyst', sa.String(length=255), nullable=True))
    op.add_column('alerts', sa.Column('entry_reference_price', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('nearest_resistance', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('resistance_source', sa.String(length=30), nullable=True))
    op.add_column('alerts', sa.Column('upside_pct', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('suggested_entry_window', sa.String(length=120), nullable=True))
    op.add_column('alerts', sa.Column('scan_timestamp', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('is_final_pass', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
    op.add_column('alerts', sa.Column('score_breakdown_json', sa.JSON(), nullable=True))
    op.alter_column('alerts', 'setup_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('alerts', 'entry_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_alerts_confidence_score'), 'alerts', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_alerts_profile'), 'alerts', ['profile'], unique=False)
    op.create_index(op.f('ix_alerts_scan_run_id'), 'alerts', ['scan_run_id'], unique=False)
    op.create_index(op.f('ix_alerts_session_date'), 'alerts', ['session_date'], unique=False)
    op.create_unique_constraint('uq_alerts_symbol_session', 'alerts', ['symbol', 'session_date'])
    # Named explicitly: autogenerate emits None here, which makes downgrade uncompilable.
    op.create_foreign_key(
        'fk_alerts_scan_run_id', 'alerts', 'scan_runs', ['scan_run_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_alerts_scan_run_id', 'alerts', type_='foreignkey')
    op.drop_constraint('uq_alerts_symbol_session', 'alerts', type_='unique')
    op.drop_index(op.f('ix_alerts_session_date'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_scan_run_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_profile'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_confidence_score'), table_name='alerts')
    op.alter_column('alerts', 'entry_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('alerts', 'setup_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('alerts', 'score_breakdown_json')
    op.drop_column('alerts', 'is_final_pass')
    op.drop_column('alerts', 'scan_timestamp')
    op.drop_column('alerts', 'suggested_entry_window')
    op.drop_column('alerts', 'upside_pct')
    op.drop_column('alerts', 'resistance_source')
    op.drop_column('alerts', 'nearest_resistance')
    op.drop_column('alerts', 'entry_reference_price')
    op.drop_column('alerts', 'catalyst')
    op.drop_column('alerts', 'rvol_is_approximate')
    op.drop_column('alerts', 'rvol_mode')
    op.drop_column('alerts', 'rvol_pct')
    op.drop_column('alerts', 'gap_pct')
    op.drop_column('alerts', 'profile')
    op.drop_column('alerts', 'session_date')
    op.drop_column('alerts', 'scan_run_id')
    op.drop_column('alerts', 'updated_at')
    op.drop_table('scanner_settings')
    # ### end Alembic commands ###
