"""Hotfix: record scan run mode

Revision ID: 3d1177ad1103
Revises: ae74a2cbe20c
Create Date: 2026-08-08 12:31:15.306816

One nullable column on `scan_runs` recording what the run was permitted to write:
`live`, `observation` or `dry_run`.

## Why it is needed

Phase 4C's two-stage go-live was specified as "full pipeline, scan_runs recorded, no alerts
persisted". It was implemented by reusing `--dry-run`, which has meant "touch nothing" since
Phase 2 — so the production cron ran a full live scan every five minutes and discarded the
result. `scan_runs` gained no rows for the entire observation window.

The flag is now `--no-alerts`, and the mode is recorded on the row so the same conflation
cannot happen silently again. Without it, a run that produced no alerts BECAUSE IT WAS NOT
ALLOWED TO is indistinguishable from one that found nothing — exactly the failure-versus-
quiet-market ambiguity the design already works to avoid elsewhere.

## Nullable, deliberately

Rows written before this column existed cannot have their mode reconstructed. Defaulting
them to `live` would assert something unknown about historical runs; NULL says "not
recorded", which is true.

## Downgrade

Drops the column. Safe on populated data — nullable, no default, nothing depends on it at
the database level. The loss is the distinction above for any run written while it existed.
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3d1177ad1103'
down_revision: Union[str, Sequence[str], None] = 'ae74a2cbe20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --------------------------------------------------------------------------------
# CREATING A TABLE? ENABLE ROW-LEVEL SECURITY.
#
#     from app.core.rls import enable_rls
#     ...
#     op.create_table("my_table", ...)
#     enable_rls("my_table")
#
# Tables in `public` without RLS are readable AND writable by anyone holding the
# Supabase anon key, straight through the auto-generated Data API — bypassing this
# backend entirely. tests/integration/test_rls.py fails CI if you forget.
# Background and the deny-all rationale: app/core/rls.py
#
# DROPPING COLUMNS OR TABLES? The downgrade has to work on a POPULATED database.
# Re-adding a NOT NULL column needs a backfill or a server_default; see the
# docstrings in 0ca0181ab014 and c653a931ecaf, and the round-trip tests in
# tests/integration/test_migration_round_trip.py.
# --------------------------------------------------------------------------------


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_runs', sa.Column('mode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_runs', 'mode')
    # ### end Alembic commands ###
