"""v2 scanner tables: universe, reference_data, premarket_volume_profile, scan_runs, api_budget

Revision ID: 5c3b382f1d74
Revises: f5e101dcbc55
Create Date: 2026-07-25 19:26:45.248545

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c3b382f1d74'
down_revision: Union[str, Sequence[str], None] = 'f5e101dcbc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('calls_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_budget_budget_date'), 'api_budget', ['budget_date'], unique=True)
    op.create_index(op.f('ix_api_budget_id'), 'api_budget', ['id'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('profile', sa.String(length=30), nullable=True),
    sa.Column('stage_counts_json', sa.JSON(), nullable=True),
    sa.Column('api_calls_used', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_runs_id'), 'scan_runs', ['id'], unique=False)
    op.create_index(op.f('ix_scan_runs_started_at'), 'scan_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_scan_runs_status'), 'scan_runs', ['status'], unique=False)
    op.create_table('universe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_accessible_free_tier', sa.Boolean(), nullable=True),
    sa.Column('probe_note', sa.Text(), nullable=True),
    sa.Column('last_probed_at', sa.DateTime(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universe_id'), 'universe', ['id'], unique=False)
    op.create_index(op.f('ix_universe_ticker'), 'universe', ['ticker'], unique=True)
    op.create_table('premarket_volume_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('bucket_minute', sa.Integer(), nullable=False),
    sa.Column('avg_cumulative_volume', sa.Float(), nullable=False),
    sa.Column('sessions_sampled', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['universe.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'bucket_minute', name='uq_premarket_profile_ticker_bucket')
    )
    op.create_index(op.f('ix_premarket_volume_profile_id'), 'premarket_volume_profile', ['id'], unique=False)
    op.create_index(op.f('ix_premarket_volume_profile_ticker'), 'premarket_volume_profile', ['ticker'], unique=False)
    op.create_table('reference_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('static_float', sa.BigInteger(), nullable=True),
    sa.Column('outstanding_shares', sa.BigInteger(), nullable=True),
    sa.Column('volume_avg_20d', sa.Float(), nullable=True),
    sa.Column('price_close_yesterday', sa.Float(), nullable=True),
    sa.Column('high_yesterday', sa.Float(), nullable=True),
    sa.Column('high_20d', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('last_bar_date', sa.Date(), nullable=True),
    sa.Column('bars_used', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['universe.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_data_computed_at'), 'reference_data', ['computed_at'], unique=False)
    op.create_index(op.f('ix_reference_data_id'), 'reference_data', ['id'], unique=False)
    op.create_index('ix_reference_data_stage1', 'reference_data', ['static_float', 'volume_avg_20d'], unique=False)
    op.create_index(op.f('ix_reference_data_ticker'), 'reference_data', ['ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_data_ticker'), table_name='reference_data')
    op.drop_index('ix_reference_data_stage1', table_name='reference_data')
    op.drop_index(op.f('ix_reference_data_id'), table_name='reference_data')
    op.drop_index(op.f('ix_reference_data_computed_at'), table_name='reference_data')
    op.drop_table('reference_data')
    op.drop_index(op.f('ix_premarket_volume_profile_ticker'), table_name='premarket_volume_profile')
    op.drop_index(op.f('ix_premarket_volume_profile_id'), table_name='premarket_volume_profile')
    op.drop_table('premarket_volume_profile')
    op.drop_index(op.f('ix_universe_ticker'), table_name='universe')
    op.drop_index(op.f('ix_universe_id'), table_name='universe')
    op.drop_table('universe')
    op.drop_index(op.f('ix_scan_runs_status'), table_name='scan_runs')
    op.drop_index(op.f('ix_scan_runs_started_at'), table_name='scan_runs')
    op.drop_index(op.f('ix_scan_runs_id'), table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_api_budget_id'), table_name='api_budget')
    op.drop_index(op.f('ix_api_budget_budget_date'), table_name='api_budget')
    op.drop_table('api_budget')
    # ### end Alembic commands ###
