"""Phase 4C: alert decision-time provenance

Revision ID: ae74a2cbe20c
Revises: b008d4bf3a18
Create Date: 2026-08-07 10:16:27.858904

Three nullable columns on `alerts` recording what the scanner saw at decision time.

Phase 4A measured that **49.4% of pre-market bars are revised upward after publication**,
all settling within ~7 minutes of the bar closing. Re-querying the same window later
therefore returns HIGHER volumes than the live scanner ever had. Without this provenance,
V3 backtesting cannot distinguish "the scanner made a bad call" from "the data was revised
after the scanner acted", and would calibrate the confidence score against numbers that
did not exist at decision time.

- `bars_settled_through`     the effective cut-off; the newest bar old enough to trust
- `provisional_bars_excluded` how many bars were dropped for being too fresh
- `profile_sessions_sampled`  how many sessions the RVOL denominator averaged

## Downgrade

All three are nullable with no default, so adding them is safe on a populated `alerts`
table and dropping them is safe too — no backfill, no NOT NULL violation. The loss is the
provenance itself: alerts written before a downgrade cannot have it reconstructed, because
the bars they were computed from have since settled to different values. That is the exact
problem these columns exist to solve, so a downgrade is a one-way door for the rows it
touches even though the schema round-trips cleanly.
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ae74a2cbe20c'
down_revision: Union[str, Sequence[str], None] = 'b008d4bf3a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --------------------------------------------------------------------------------
# CREATING A TABLE? ENABLE ROW-LEVEL SECURITY.
#
#     from app.core.rls import enable_rls
#     ...
#     op.create_table("my_table", ...)
#     enable_rls("my_table")
#
# Tables in `public` without RLS are readable AND writable by anyone holding the
# Supabase anon key, straight through the auto-generated Data API — bypassing this
# backend entirely. tests/integration/test_rls.py fails CI if you forget.
# Background and the deny-all rationale: app/core/rls.py
#
# DROPPING COLUMNS OR TABLES? The downgrade has to work on a POPULATED database.
# Re-adding a NOT NULL column needs a backfill or a server_default; see the
# docstrings in 0ca0181ab014 and c653a931ecaf, and the round-trip tests in
# tests/integration/test_migration_round_trip.py.
# --------------------------------------------------------------------------------


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('bars_settled_through', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('provisional_bars_excluded', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('profile_sessions_sampled', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'profile_sessions_sampled')
    op.drop_column('alerts', 'provisional_bars_excluded')
    op.drop_column('alerts', 'bars_settled_through')
    # ### end Alembic commands ###
